name: Find out whether a PR is a draft
inputs:
  organization:
    description: "The name of the organization under which the project is saved"
    required: true
    type: string
  repository:
    description: "The name of the repository in which the PR is located"
    required: true
    type: string
  pr_num:
    description: "The number of the PR within the repository"
    required: true
    type: string
outputs:
  is_draft:
    description: "Whether this PR is a draft"
    value: ${{ steps.step.outputs.is_draft  }}

runs:
  using: "composite"
  steps:
    - id: step
      shell: bash
      run: |
        json=$(gh api graphql -f query='query FindAffectedIssues {
          repository(name: "${{ inputs.repository }}", owner: "${{ inputs.organization }}") {
            pullRequest(number: ${{ inputs.pr_num }}) {
              isDraft
            }
          }
        }' | jq -c '.data.repository.pullRequest')
        echo "is_draft=$(echo ${json} | jq -c '.isDraft')" >> $GITHUB_OUTPUT
