name: Move linked issues to "In Review"

# This is what you probably want to have in your workflow YAML
#
# on:
#   pull_request:
#     types: [opened, edited, ready_for_review]

on:
  workflow_call:
    inputs:
      organization:
        description: "The name of the organization under which the project is saved"
        required: true
        type: string
      project:
        description: "The name of the project within which the issue should be moved"
        required: true
        type: string
      column:
        description: "The column to which the issue should be moved"
        required: false
        type: string
        default: "In Review"
    secrets:
        gh_token:
          description: "Token with which the GH client can be used"
          required: true

env:
  PR_NUM: ${{ github.event.number }}
  REPOSITORY: "${{ github.event.repository.name }}"
  GH_TOKEN: ${{ secrets.gh_token }}

jobs:
  InReviewOnPR:
    runs-on: ubuntu-latest
    steps:
      - id: find_project_id_and_number
        uses: alpico/workflows/.github/actions/find_project_id_and_number@experiment
        with:
          organization: ${{ inputs.organization }}
          project: ${{ inputs.project }}

      - id: is_pr_draft
        uses: alpico/workflows/.github/actions/is_pr_draft@experiment
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ env.REPOSITORY }}
          pr_num: ${{ env.PR_NUM }}

      - if: ${{ !(steps.is_pr_draft.outputs.is_draft == 'true') }}
        id: find_closing_issues
        uses: alpico/workflows/.github/actions/find_closing_issues@experiment
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ env.REPOSITORY }}
          pr_num: ${{ env.PR_NUM }}

      - run: echo "EXIT_EARLY=${{ steps.is_pr_draft.outputs.is_draft == 'true' || steps.find_closing_issues.outputs.issue_ids == '[]' }}" >> $GITHUB_ENV

      - if: ${{ env.EXIT_EARLY != 'true' }}
        id: find_field_and_column_id
        uses: alpico/workflows/.github/actions/find_field_and_column_id@experiment
        with:
          organization: ${{ inputs.organization }}
          project_number: ${{ steps.find_project_id_and_number.outputs.project_number }}
          column: ${{ inputs.column }}

      - if: ${{ env.EXIT_EARLY != 'true' }}
        id: project_item_ids_from_issue_urls
        uses: alpico/workflows/.github/actions/project_item_ids_from_issue_urls@experiment
        with:
          organization: ${{ inputs.organization }}
          project_number: ${{ steps.find_project_id_and_number.outputs.project_number }}
          issue_ids: ${{ steps.find_closing_issues.outputs.issue_ids }}

      - if: ${{ env.EXIT_EARLY != 'true' }}
        id: move_items_to_column
        uses: alpico/workflows/.github/actions/move_items_to_column@experiment
        with:
          organization: ${{ inputs.organization }}
          project_id: ${{ steps.find_project_id_and_number.outputs.project_id }}
          item_ids: ${{ steps.project_item_ids_from_issue_urls.outputs.item_ids }}
          column_id: ${{ steps.find_field_and_column_id.outputs.column_id }}
          field_id: ${{ steps.find_field_and_column_id.outputs.field_id }}
